#############################################################################
# Makefile for building: Audo
# Generated by qmake (2.01a) (Qt 4.4.0-beta1) on: Thu Dec 11 18:00:33 2008
# Project:  Audo.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Audo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lQtGui -L/usr/lib/qt4 -L/usr/X11R6/lib -lpng -lSM -lICE -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/audo.cpp \
		src/aueditsubwindow.cpp \
		src/aumainwindow.cpp \
		src/aumdiarea.cpp \
		src/auwavedisplay.cpp \
		src/buffer.cpp moc_aumainwindow.cpp \
		moc_auwavedisplay.cpp
OBJECTS       = audo.o \
		aueditsubwindow.o \
		aumainwindow.o \
		aumdiarea.o \
		auwavedisplay.o \
		buffer.o \
		moc_aumainwindow.o \
		moc_auwavedisplay.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Audo.pro
QMAKE_TARGET  = Audo
DESTDIR       = 
TARGET        = Audo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Audo.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtCore.prl
	$(QMAKE) -unix -o Makefile Audo.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Audo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Audo1.0.0 || $(MKDIR) .tmp/Audo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Audo1.0.0/ && $(COPY_FILE) --parents include/aueditsubwindow.h include/aumainwindow.h include/aumdiarea.h include/auwavedisplay.h include/buffer.h .tmp/Audo1.0.0/ && $(COPY_FILE) --parents src/audo.cpp src/aueditsubwindow.cpp src/aumainwindow.cpp src/aumdiarea.cpp src/auwavedisplay.cpp src/buffer.cpp .tmp/Audo1.0.0/ && (cd `dirname .tmp/Audo1.0.0` && $(TAR) Audo1.0.0.tar Audo1.0.0 && $(COMPRESS) Audo1.0.0.tar) && $(MOVE) `dirname .tmp/Audo1.0.0`/Audo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Audo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aumainwindow.cpp moc_auwavedisplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aumainwindow.cpp moc_auwavedisplay.cpp
moc_aumainwindow.cpp: include/aumdiarea.h \
		include/aumainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/aumainwindow.h -o moc_aumainwindow.cpp

moc_auwavedisplay.cpp: include/buffer.h \
		include/auwavedisplay.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/auwavedisplay.h -o moc_auwavedisplay.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

audo.o: src/audo.cpp include/aumainwindow.h \
		include/aumdiarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audo.o src/audo.cpp

aueditsubwindow.o: src/aueditsubwindow.cpp include/aueditsubwindow.h \
		include/auwavedisplay.h \
		include/buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aueditsubwindow.o src/aueditsubwindow.cpp

aumainwindow.o: src/aumainwindow.cpp include/aumainwindow.h \
		include/aumdiarea.h \
		include/aueditsubwindow.h \
		include/auwavedisplay.h \
		include/buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aumainwindow.o src/aumainwindow.cpp

aumdiarea.o: src/aumdiarea.cpp include/aumdiarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aumdiarea.o src/aumdiarea.cpp

auwavedisplay.o: src/auwavedisplay.cpp include/auwavedisplay.h \
		include/buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auwavedisplay.o src/auwavedisplay.cpp

buffer.o: src/buffer.cpp include/buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buffer.o src/buffer.cpp

moc_aumainwindow.o: moc_aumainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aumainwindow.o moc_aumainwindow.cpp

moc_auwavedisplay.o: moc_auwavedisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_auwavedisplay.o moc_auwavedisplay.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

