#############################################################################
# Makefile for building: Audo
# Generated by qmake (2.01a) (Qt 4.5.2) on: Thu Dec 3 15:07:44 2009
# Project:  Audo.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Audo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc/controller -Isrc/model -Isrc/util -Isrc/gui -Isrc/view -Isrc/input -Isrc/output -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lsndfile -lQtGui -L/usr/lib -L/usr/X11R6/lib -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/controller/ActionController.cpp \
		src/controller/FileNewController.cpp \
		src/controller/FileOpenController.cpp \
		src/gui/Audo.cpp \
		src/gui/EditSubWindow.cpp \
		src/gui/MainWindow.cpp \
		src/gui/MDIArea.cpp \
		src/input/AudioReader.cpp \
		src/model/Buffer.cpp \
		src/model/BufferPool.cpp \
		src/model/StandardBuffer.cpp \
		src/output/JackOutput.cpp \
		src/view/WaveDisplay.cpp moc_ActionController.cpp \
		moc_FileNewController.cpp \
		moc_FileOpenController.cpp \
		moc_EditSubWindow.cpp \
		moc_MainWindow.cpp \
		moc_WaveDisplay.cpp
OBJECTS       = ActionController.o \
		FileNewController.o \
		FileOpenController.o \
		Audo.o \
		EditSubWindow.o \
		MainWindow.o \
		MDIArea.o \
		AudioReader.o \
		Buffer.o \
		BufferPool.o \
		StandardBuffer.o \
		JackOutput.o \
		WaveDisplay.o \
		moc_ActionController.o \
		moc_FileNewController.o \
		moc_FileOpenController.o \
		moc_EditSubWindow.o \
		moc_MainWindow.o \
		moc_WaveDisplay.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		Extra.pro \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		Audo.pro
QMAKE_TARGET  = Audo
DESTDIR       = 
TARGET        = Audo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Audo.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		Extra.pro \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Audo.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
Extra.pro:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Audo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Audo1.0.0 || $(MKDIR) .tmp/Audo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Audo1.0.0/ && $(COPY_FILE) --parents src/controller/ActionController.h src/controller/FileNewController.h src/controller/FileOpenController.h src/gui/EditSubWindow.h src/gui/MainWindow.h src/gui/MDIArea.h src/input/AudioReader.h src/model/Buffer.h src/model/BufferPool.h src/model/BufferRef.h src/model/StandardBuffer.h src/output/JackOutput.h src/output/Output.h src/util/AudoTypes.h src/util/singleton.h src/view/WaveDisplay.h src/util/log/Logger.h src/util/log/StreamLogger.h .tmp/Audo1.0.0/ && $(COPY_FILE) --parents src/controller/ActionController.cpp src/controller/FileNewController.cpp src/controller/FileOpenController.cpp src/gui/Audo.cpp src/gui/EditSubWindow.cpp src/gui/MainWindow.cpp src/gui/MDIArea.cpp src/input/AudioReader.cpp src/model/Buffer.cpp src/model/BufferPool.cpp src/model/StandardBuffer.cpp src/output/JackOutput.cpp src/view/WaveDisplay.cpp .tmp/Audo1.0.0/ && (cd `dirname .tmp/Audo1.0.0` && $(TAR) Audo1.0.0.tar Audo1.0.0 && $(COMPRESS) Audo1.0.0.tar) && $(MOVE) `dirname .tmp/Audo1.0.0`/Audo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Audo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ActionController.cpp moc_FileNewController.cpp moc_FileOpenController.cpp moc_EditSubWindow.cpp moc_MainWindow.cpp moc_WaveDisplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ActionController.cpp moc_FileNewController.cpp moc_FileOpenController.cpp moc_EditSubWindow.cpp moc_MainWindow.cpp moc_WaveDisplay.cpp
moc_ActionController.cpp: src/controller/ActionController.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/controller/ActionController.h -o moc_ActionController.cpp

moc_FileNewController.cpp: src/controller/ActionController.h \
		src/model/BufferPool.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h \
		src/util/AudoTypes.h \
		src/controller/FileNewController.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/controller/FileNewController.h -o moc_FileNewController.cpp

moc_FileOpenController.cpp: src/controller/ActionController.h \
		src/controller/FileOpenController.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/controller/FileOpenController.h -o moc_FileOpenController.cpp

moc_EditSubWindow.cpp: src/view/WaveDisplay.h \
		src/model/Buffer.h \
		src/input/AudioReader.h \
		src/model/StandardBuffer.h \
		src/gui/EditSubWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/EditSubWindow.h -o moc_EditSubWindow.cpp

moc_MainWindow.cpp: src/gui/MDIArea.h \
		src/controller/FileNewController.h \
		src/controller/ActionController.h \
		src/model/BufferPool.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h \
		src/util/AudoTypes.h \
		src/controller/FileOpenController.h \
		src/gui/MainWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/MainWindow.h -o moc_MainWindow.cpp

moc_WaveDisplay.cpp: src/model/Buffer.h \
		src/view/WaveDisplay.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/view/WaveDisplay.h -o moc_WaveDisplay.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

ActionController.o: src/controller/ActionController.cpp src/controller/ActionController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ActionController.o src/controller/ActionController.cpp

FileNewController.o: src/controller/FileNewController.cpp src/controller/FileNewController.h \
		src/controller/ActionController.h \
		src/model/BufferPool.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h \
		src/util/AudoTypes.h \
		src/gui/EditSubWindow.h \
		src/view/WaveDisplay.h \
		src/input/AudioReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileNewController.o src/controller/FileNewController.cpp

FileOpenController.o: src/controller/FileOpenController.cpp src/gui/EditSubWindow.h \
		src/view/WaveDisplay.h \
		src/model/Buffer.h \
		src/input/AudioReader.h \
		src/model/StandardBuffer.h \
		src/controller/FileOpenController.h \
		src/controller/ActionController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileOpenController.o src/controller/FileOpenController.cpp

Audo.o: src/gui/Audo.cpp src/gui/MainWindow.h \
		src/gui/MDIArea.h \
		src/controller/FileNewController.h \
		src/controller/ActionController.h \
		src/model/BufferPool.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h \
		src/util/AudoTypes.h \
		src/controller/FileOpenController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Audo.o src/gui/Audo.cpp

EditSubWindow.o: src/gui/EditSubWindow.cpp src/gui/EditSubWindow.h \
		src/view/WaveDisplay.h \
		src/model/Buffer.h \
		src/input/AudioReader.h \
		src/model/StandardBuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditSubWindow.o src/gui/EditSubWindow.cpp

MainWindow.o: src/gui/MainWindow.cpp src/gui/MainWindow.h \
		src/gui/MDIArea.h \
		src/controller/FileNewController.h \
		src/controller/ActionController.h \
		src/model/BufferPool.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h \
		src/util/AudoTypes.h \
		src/controller/FileOpenController.h \
		src/gui/EditSubWindow.h \
		src/view/WaveDisplay.h \
		src/input/AudioReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/gui/MainWindow.cpp

MDIArea.o: src/gui/MDIArea.cpp src/gui/MDIArea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MDIArea.o src/gui/MDIArea.cpp

AudioReader.o: src/input/AudioReader.cpp src/input/AudioReader.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioReader.o src/input/AudioReader.cpp

Buffer.o: src/model/Buffer.cpp src/model/Buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Buffer.o src/model/Buffer.cpp

BufferPool.o: src/model/BufferPool.cpp src/model/BufferPool.h \
		src/model/StandardBuffer.h \
		src/model/Buffer.h \
		src/util/AudoTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BufferPool.o src/model/BufferPool.cpp

StandardBuffer.o: src/model/StandardBuffer.cpp src/model/StandardBuffer.h \
		src/model/Buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StandardBuffer.o src/model/StandardBuffer.cpp

JackOutput.o: src/output/JackOutput.cpp src/output/JackOutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JackOutput.o src/output/JackOutput.cpp

WaveDisplay.o: src/view/WaveDisplay.cpp src/view/WaveDisplay.h \
		src/model/Buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaveDisplay.o src/view/WaveDisplay.cpp

moc_ActionController.o: moc_ActionController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ActionController.o moc_ActionController.cpp

moc_FileNewController.o: moc_FileNewController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FileNewController.o moc_FileNewController.cpp

moc_FileOpenController.o: moc_FileOpenController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FileOpenController.o moc_FileOpenController.cpp

moc_EditSubWindow.o: moc_EditSubWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditSubWindow.o moc_EditSubWindow.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_WaveDisplay.o: moc_WaveDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WaveDisplay.o moc_WaveDisplay.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

